spring:
  application:
    name: eureka-ribbon

server:
  port: 8888

#say-hello:
#  ribbon:
#    eureka:
#      enabled: false
#    listOfServers: localhost:8090,localhost:9092,localhost:9999
#    ServerListRefreshInterval: 15000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
