server:
  port: 8761
  
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    
  server:
    enable-self-preservation: true
    renewal-percent-threshold: 0.45

logging:
  level:
    com.netflix.eureka: off
    com.netflix.discovery: off

